import mongoose from 'mongoose';

export const ORDER_STATUSES = [
  'pending',
  'payment_processing',
  'payment_confirmed',
  'confirmed',
  'packed',
  'shipped',
  'delivered',
  'cancelled',
  'return_requested',
  'returned',
  'refund_initiated',
  'refunded',
];

/** Statuses that represent forward progress in the customer tracker. */
export const FULFILMENT_FLOW = ['pending', 'payment_confirmed', 'confirmed', 'packed', 'shipped', 'delivered'];

const orderItemSchema = new mongoose.Schema({
  product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true, index: true },
  variantId: { type: mongoose.Schema.Types.ObjectId, default: null },
  // Snapshot fields keep the order readable even if the product later changes.
  name: { type: String, required: true },
  slug: { type: String, required: true },
  sku: { type: String, required: true },
  image: { type: String, default: '' },
  color: { type: String, default: '' },
  size: { type: String, default: '' },
  unitPrice: { type: Number, required: true, min: 0 },
  originalPrice: { type: Number, default: null },
  quantity: { type: Number, required: true, min: 1 },
  lineTotal: { type: Number, required: true, min: 0 },
}, { _id: true });

const statusEventSchema = new mongoose.Schema({
  status: { type: String, enum: ORDER_STATUSES, required: true },
  note: { type: String, default: '' },
  at: { type: Date, default: Date.now },
  by: { type: String, default: 'system' },
}, { _id: false });

const shippingAddressSchema = new mongoose.Schema({
  fullName: { type: String, required: true },
  mobile: { type: String, required: true },
  house: { type: String, required: true },
  street: { type: String, default: '' },
  area: { type: String, default: '' },
  city: { type: String, required: true },
  state: { type: String, required: true },
  pincode: { type: String, required: true },
  country: { type: String, default: 'India' },
}, { _id: false });

const orderSchema = new mongoose.Schema({
  orderNumber: { type: String, required: true, unique: true, index: true },
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null, index: true },

  customer: {
    name: { type: String, required: true },
    email: { type: String, required: true, lowercase: true, index: true },
    mobile: { type: String, required: true },
  },

  items: { type: [orderItemSchema], validate: [(v) => v.length > 0, 'Order must contain at least one item'] },
  shippingAddress: { type: shippingAddressSchema, required: true },

  subtotal: { type: Number, required: true, min: 0 },
  discount: { type: Number, default: 0, min: 0 },
  couponCode: { type: String, default: '' },
  shippingFee: { type: Number, default: 0, min: 0 },
  total: { type: Number, required: true, min: 0 },

  paymentMethod: { type: String, enum: ['cod', 'upi', 'card', 'netbanking', 'wallet', 'online'], required: true },
  paymentStatus: { type: String, enum: ['pending', 'processing', 'paid', 'failed', 'refunded'], default: 'pending', index: true },
  payment: {
    provider: { type: String, default: '' },
    orderId: { type: String, default: '' },
    paymentId: { type: String, default: '' },
    signature: { type: String, default: '' },
    paidAt: { type: Date, default: null },
  },

  status: { type: String, enum: ORDER_STATUSES, default: 'pending', index: true },
  statusHistory: { type: [statusEventSchema], default: [] },

  trackingNumber: { type: String, default: '' },
  courier: { type: String, default: '' },
  customerNote: { type: String, default: '' },
  adminNote: { type: String, default: '' },
  cancellationReason: { type: String, default: '' },
  returnReason: { type: String, default: '' },

  // True only for records generated by the seeder.
  isDemo: { type: Boolean, default: false, index: true },
  // Set once stock has been deducted so restocking stays idempotent.
  stockDeducted: { type: Boolean, default: false },
  stockRestored: { type: Boolean, default: false },
}, { timestamps: true });

orderSchema.index({ createdAt: -1 });
orderSchema.index({ 'customer.email': 1, createdAt: -1 });

orderSchema.statics.generateOrderNumber = async function generateOrderNumber() {
  const now = new Date();
  const datePart = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}`;
  for (let attempt = 0; attempt < 6; attempt += 1) {
    const random = Math.floor(1000 + Math.random() * 9000);
    const candidate = `AAR-${datePart}-${random}`;
    // eslint-disable-next-line no-await-in-loop
    const exists = await this.exists({ orderNumber: candidate });
    if (!exists) return candidate;
  }
  return `AAR-${datePart}-${Date.now().toString().slice(-6)}`;
};

export const Order = mongoose.model('Order', orderSchema);
