/* ------------------------------------------------------------------
   Achievement catalogue — unlocked by the store whenever stats change.
------------------------------------------------------------------ */
import type { Achievement } from './types'

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-workout',
    name: 'First Workout',
    description: 'Complete your very first session',
    emoji: '🏆',
    tier: 'bronze',
    metric: 'sessions',
    threshold: 1,
  },
  {
    id: 'workouts-10',
    name: '10 Workouts Completed',
    description: 'Ten sessions in the bank',
    emoji: '💪',
    tier: 'silver',
    metric: 'sessions',
    threshold: 10,
  },
  {
    id: 'workouts-25',
    name: 'Consistency Machine',
    description: 'Complete 25 workouts',
    emoji: '🥇',
    tier: 'gold',
    metric: 'sessions',
    threshold: 25,
  },
  {
    id: 'workouts-100',
    name: 'Century Club',
    description: 'Complete 100 workouts',
    emoji: '👑',
    tier: 'platinum',
    metric: 'sessions',
    threshold: 100,
  },
  {
    id: 'streak-3',
    name: '3 Day Streak',
    description: 'Show up three days in a row',
    emoji: '🔥',
    tier: 'bronze',
    metric: 'streak',
    threshold: 3,
  },
  {
    id: 'streak-7',
    name: '7 Day Streak',
    description: 'A full week without missing',
    emoji: '🔥',
    tier: 'silver',
    metric: 'streak',
    threshold: 7,
  },
  {
    id: 'streak-30',
    name: '30 Day Streak',
    description: 'A month of unbroken training',
    emoji: '🌋',
    tier: 'platinum',
    metric: 'streak',
    threshold: 30,
  },
  {
    id: 'steps-10k',
    name: 'First 10k Steps',
    description: 'Walk 10,000 steps in total',
    emoji: '🚶',
    tier: 'bronze',
    metric: 'steps',
    threshold: 10000,
  },
  {
    id: 'steps-50k',
    name: '50,000 Steps',
    description: 'Fifty thousand steps logged',
    emoji: '🏃',
    tier: 'silver',
    metric: 'steps',
    threshold: 50000,
  },
  {
    id: 'steps-250k',
    name: 'Road Runner',
    description: 'A quarter of a million steps',
    emoji: '🛣️',
    tier: 'gold',
    metric: 'steps',
    threshold: 250000,
  },
  {
    id: 'water-10l',
    name: '10L Water',
    description: 'Drink 10 litres of water',
    emoji: '💧',
    tier: 'bronze',
    metric: 'water',
    threshold: 10,
  },
  {
    id: 'water-100l',
    name: 'Hydration Hero',
    description: 'Drink 100 litres of water',
    emoji: '🌊',
    tier: 'gold',
    metric: 'water',
    threshold: 100,
  },
  {
    id: 'calories-5000',
    name: '5,000 kcal Burned',
    description: 'Torch five thousand calories',
    emoji: '⚡',
    tier: 'silver',
    metric: 'calories',
    threshold: 5000,
  },
  {
    id: 'minutes-600',
    name: '10 Hours Trained',
    description: 'Train for 600 minutes',
    emoji: '⏱️',
    tier: 'silver',
    metric: 'minutes',
    threshold: 600,
  },
  {
    id: 'goal-1',
    name: 'Goal Completed',
    description: 'Reach a personal goal target',
    emoji: '🎯',
    tier: 'bronze',
    metric: 'goals',
    threshold: 1,
  },
  {
    id: 'goal-5',
    name: 'Goal Machine',
    description: 'Complete five personal goals',
    emoji: '🧭',
    tier: 'gold',
    metric: 'goals',
    threshold: 5,
  },
]

export const TIER_STYLES: Record<Achievement['tier'], { ring: string; bg: string; text: string; label: string }> = {
  bronze: { ring: 'ring-amber/30', bg: 'bg-amber/10', text: 'text-amber', label: 'Bronze' },
  silver: { ring: 'ring-water/30', bg: 'bg-water/10', text: 'text-water', label: 'Silver' },
  gold: { ring: 'ring-brand/40', bg: 'bg-brand/12', text: 'text-brand', label: 'Gold' },
  platinum: { ring: 'ring-violet/40', bg: 'bg-violet/12', text: 'text-violet', label: 'Platinum' },
}
