/* ------------------------------------------------------------------
   Exercise library — the single catalogue the whole app reads from.
   `met` values come from the Compendium of Physical Activities and are
   used to compute real calorie burn from the user's body weight.
------------------------------------------------------------------ */
import type { Exercise, WorkoutExercise } from './types'

interface ExerciseSeed {
  id: string
  name: string
  group: Exercise['group']
  equipment: Exercise['equipment']
  pose: Exercise['pose']
  met: number
  tip: string
  instructions: string[]
}

const seed = (rows: ExerciseSeed[]): Exercise[] => rows.map((row) => ({ ...row }))

export const EXERCISES: Exercise[] = seed([
  /* ------------------------------- chest ------------------------------- */
  {
    id: 'push-up',
    name: 'Push Ups',
    group: 'Chest',
    equipment: 'None',
    pose: 'pushup',
    met: 8,
    tip: 'Keep a straight line from head to heels — squeeze the glutes.',
    instructions: ['Hands slightly wider than shoulders', 'Lower with control until elbows hit 90°', 'Drive back up without flaring the ribs'],
  },
  {
    id: 'incline-push-up',
    name: 'Incline Push Ups',
    group: 'Chest',
    equipment: 'None',
    pose: 'pushup',
    met: 7,
    tip: 'Hands on a bench shifts load away from the wrists.',
    instructions: ['Place hands on a stable elevated surface', 'Keep elbows at 45° from the torso', 'Press away and lock the core'],
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    group: 'Chest',
    equipment: 'Dumbbells',
    pose: 'press',
    met: 6,
    tip: 'Pause for one second at the bottom to kill momentum.',
    instructions: ['Shoulder blades pinned to the bench', 'Lower dumbbells to chest level', 'Press up and slightly inward'],
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    group: 'Chest',
    equipment: 'Dumbbells',
    pose: 'press',
    met: 6.5,
    tip: 'Set the bench to ~30° for upper-chest emphasis.',
    instructions: ['Bench at 30–40°', 'Wrists stacked over elbows', 'Stop just short of locking out'],
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    group: 'Chest',
    equipment: 'Dumbbells',
    pose: 'press',
    met: 5.5,
    tip: 'Think about hugging a tree — slight elbow bend throughout.',
    instructions: ['Arms open in a wide arc', 'Feel the stretch across the chest', 'Squeeze back to the start'],
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push Ups',
    group: 'Shoulders',
    equipment: 'None',
    pose: 'pushup',
    met: 6,
    tip: 'Hips high, crown of the head to the floor.',
    instructions: ['Start in a downward-dog shape', 'Bend elbows to lower the head', 'Press back to the pike'],
  },
  {
    id: 'shoulder-press',
    name: 'Shoulder Press',
    group: 'Shoulders',
    equipment: 'Dumbbells',
    pose: 'press',
    met: 5,
    tip: 'Brace the abs so the ribs do not flare at lockout.',
    instructions: ['Dumbbells at shoulder height', 'Press overhead in a slight arc', 'Lower to ear level with control'],
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raises',
    group: 'Shoulders',
    equipment: 'Dumbbells',
    pose: 'press',
    met: 4,
    tip: 'Lead with the elbows and stop at shoulder height.',
    instructions: ['Arms slightly bent at the sides', 'Raise out to shoulder height', 'Lower slowly against gravity'],
  },
  {
    id: 'front-raise',
    name: 'Front Raises',
    group: 'Shoulders',
    equipment: 'Dumbbells',
    pose: 'press',
    met: 4,
    tip: 'No swinging — the hips stay still.',
    instructions: ['Weights in front of the thighs', 'Raise to eye level', 'Lower with a three-second tempo'],
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    group: 'Shoulders',
    equipment: 'Dumbbells',
    pose: 'row',
    met: 4.5,
    tip: 'Thumbs down, small range, big squeeze.',
    instructions: ['Hinge forward with a flat back', 'Open the arms wide', 'Squeeze the shoulder blades together'],
  },
  /* -------------------------------- back -------------------------------- */
  {
    id: 'bent-over-row',
    name: 'Bent Over Rows',
    group: 'Back',
    equipment: 'Dumbbells',
    pose: 'row',
    met: 6,
    tip: 'Pull with the elbows, not the hands. No jerking.',
    instructions: ['Hinge to 45° with a neutral spine', 'Row toward the lower ribs', 'Lower slowly for 2 seconds'],
  },
  {
    id: 'pull-up',
    name: 'Pull Ups',
    group: 'Back',
    equipment: 'Pull-up Bar',
    pose: 'pullup',
    met: 8,
    tip: 'Start each rep from a dead hang for full range.',
    instructions: ['Overhand grip, hands shoulder-width', 'Drive elbows down to the ribs', 'Chin clears the bar, then lower with control'],
  },
  {
    id: 'inverted-row',
    name: 'Inverted Rows',
    group: 'Back',
    equipment: 'None',
    pose: 'row',
    met: 5.5,
    tip: 'The lower the bar, the harder the row.',
    instructions: ['Hang under a bar with straight arms', 'Keep hips in line with shoulders', 'Touch the chest to the bar'],
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    group: 'Back',
    equipment: 'Machine',
    pose: 'pullup',
    met: 5,
    tip: 'Lead with the chest up, avoid leaning far back.',
    instructions: ['Grip slightly wider than shoulders', 'Pull the bar to the collarbone', 'Return with a 3-second negative'],
  },
  {
    id: 'superman',
    name: 'Superman Hold',
    group: 'Back',
    equipment: 'None',
    pose: 'bridge',
    met: 3.5,
    tip: 'Lift from the mid-back, keep the neck long.',
    instructions: ['Lie face down, arms extended', 'Lift chest, arms and legs together', 'Hold and breathe steadily'],
  },
  {
    id: 'reverse-snow-angel',
    name: 'Reverse Snow Angels',
    group: 'Back',
    equipment: 'None',
    pose: 'stretch',
    met: 3,
    tip: 'Keep the hands off the floor the whole time.',
    instructions: ['Lie face down with arms by the sides', 'Sweep arms overhead and back', 'Lead with the thumbs'],
  },
  /* -------------------------------- legs -------------------------------- */
  {
    id: 'bodyweight-squat',
    name: 'Squats',
    group: 'Legs',
    equipment: 'None',
    pose: 'squat',
    met: 5.5,
    tip: 'Knees track over the toes, chest stays proud.',
    instructions: ['Feet shoulder-width, toes slightly out', 'Sit back and down to parallel', 'Drive through the mid-foot to stand'],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    group: 'Legs',
    equipment: 'Kettlebell',
    pose: 'squat',
    met: 6,
    tip: 'Elbows inside the knees at the bottom.',
    instructions: ['Hold the bell at chest height', 'Squat between the hips', 'Keep the torso tall'],
  },
  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    group: 'Legs',
    equipment: 'Barbell',
    pose: 'squat',
    met: 6,
    tip: 'Brace the core before every rep — no breath, no rep.',
    instructions: ['Bar on the upper traps, feet planted', 'Break at the hips and knees together', 'Stand and re-brace each rep'],
  },
  {
    id: 'walking-lunge',
    name: 'Walking Lunges',
    group: 'Legs',
    equipment: 'None',
    pose: 'lunge',
    met: 5,
    tip: 'Long steps hit the glutes; short steps hit the quads.',
    instructions: ['Step forward into a 90/90 position', 'Keep the front knee over the ankle', 'Push through the heel to the next step'],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    group: 'Legs',
    equipment: 'Dumbbells',
    pose: 'lunge',
    met: 6.5,
    tip: 'Rear foot on a chair, front shin vertical.',
    instructions: ['Back foot elevated behind you', 'Drop straight down', 'Drive up through the front leg'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    group: 'Legs',
    equipment: 'Barbell',
    pose: 'bridge',
    met: 6,
    tip: 'Hinge until you feel the hamstrings, then stop.',
    instructions: ['Soft knees, shoulders back and down', 'Slide the bar down the thighs', 'Stand by squeezing the glutes'],
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    group: 'Glutes',
    equipment: 'Mat',
    pose: 'bridge',
    met: 4,
    tip: 'Posterior pelvic tilt at the top — rip the floor apart.',
    instructions: ['Heels close to the hips', 'Press hips up until thighs align', 'Hold for a beat at the top'],
  },
  {
    id: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    group: 'Glutes',
    equipment: 'Barbell',
    pose: 'bridge',
    met: 6,
    tip: 'Chin tucked, ribs down — drive with the hips.',
    instructions: ['Upper back on the bench, bar across hips', 'Drive up to a flat torso', 'Pause, then lower under control'],
  },
  {
    id: 'calf-raise',
    name: 'Calf Raises',
    group: 'Legs',
    equipment: 'None',
    pose: 'stretch',
    met: 4,
    tip: 'Pause at the top for a two-second squeeze.',
    instructions: ['Stand tall on a step edge', 'Rise onto the balls of the feet', 'Lower slowly for a deep stretch'],
  },
  {
    id: 'step-up',
    name: 'Step Ups',
    group: 'Legs',
    equipment: 'None',
    pose: 'lunge',
    met: 6,
    tip: 'Drive through the top knee — no bouncing off the floor.',
    instructions: ['Place the whole foot on the box', 'Stand up fully on one leg', 'Lower with control, alternate legs'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    group: 'Legs',
    equipment: 'Machine',
    pose: 'squat',
    met: 5,
    tip: 'Never let the lower back round off the pad.',
    instructions: ['Feet shoulder-width on the platform', 'Lower until knees reach 90°', 'Press without locking the knees'],
  },
  {
    id: 'lateral-band-walk',
    name: 'Lateral Band Walk',
    group: 'Glutes',
    equipment: 'Resistance Band',
    pose: 'squat',
    met: 5,
    tip: 'Band above the knees, keep constant tension.',
    instructions: ['Quarter-squat stance', 'Step sideways against the band', 'Alternate direction each set'],
  },
  {
    id: 'donkey-kick',
    name: 'Donkey Kicks',
    group: 'Glutes',
    equipment: 'Mat',
    pose: 'stretch',
    met: 4,
    tip: 'Keep the pelvis square — no twisting.',
    instructions: ['On all fours, core braced', 'Kick one heel to the ceiling', 'Squeeze the glute at the top'],
  },
  /* -------------------------------- arms -------------------------------- */
  {
    id: 'bicep-curl',
    name: 'Bicep Curls',
    group: 'Arms',
    equipment: 'Dumbbells',
    pose: 'curl',
    met: 3.5,
    tip: 'Elbows pinned to the ribs — the torso does not swing.',
    instructions: ['Palms forward, arms long', 'Curl to a full squeeze', 'Lower for three slow seconds'],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curls',
    group: 'Arms',
    equipment: 'Dumbbells',
    pose: 'curl',
    met: 3.5,
    tip: 'Neutral grip builds the brachialis for thicker arms.',
    instructions: ['Palms facing each other', 'Curl without rotating the wrist', 'Control the descent'],
  },
  {
    id: 'tricep-dip',
    name: 'Tricep Dips',
    group: 'Arms',
    equipment: 'None',
    pose: 'pushup',
    met: 6,
    tip: 'Keep the shoulders down, chest up.',
    instructions: ['Hands on a bench behind you', 'Bend elbows to 90°', 'Press the bench away'],
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    group: 'Arms',
    equipment: 'Dumbbells',
    pose: 'press',
    met: 4,
    tip: 'Keep the elbows narrow and pointed at the ceiling.',
    instructions: ['Hold one dumbbell overhead', 'Lower behind the head', 'Extend without flaring'],
  },
  {
    id: 'tricep-kickback',
    name: 'Tricep Kickbacks',
    group: 'Arms',
    equipment: 'Dumbbells',
    pose: 'curl',
    met: 4,
    tip: 'Upper arm stays parallel to the floor.',
    instructions: ['Hinge forward, elbows at 90°', 'Kick the forearm back', 'Squeeze, then return slowly'],
  },
  /* -------------------------------- core -------------------------------- */
  {
    id: 'plank',
    name: 'Plank',
    group: 'Core',
    equipment: 'Mat',
    pose: 'plank',
    met: 3.5,
    tip: 'Squeeze glutes and quads — the abs follow.',
    instructions: ['Forearms under the shoulders', 'Ribs down, hips level', 'Breathe slowly through the hold'],
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    group: 'Core',
    equipment: 'Mat',
    pose: 'plank',
    met: 3.5,
    tip: 'Stack the hips — no sagging toward the floor.',
    instructions: ['Elbow under the shoulder, feet stacked', 'Lift the hips into a line', 'Hold, then switch sides'],
  },
  {
    id: 'bicycle-crunch',
    name: 'Bicycle Crunches',
    group: 'Core',
    equipment: 'Mat',
    pose: 'twist',
    met: 5,
    tip: 'Slow and controlled beats fast and sloppy.',
    instructions: ['Hands lightly behind the head', 'Rotate shoulder to opposite knee', 'Extend the other leg long'],
  },
  {
    id: 'crunch',
    name: 'Crunches',
    group: 'Core',
    equipment: 'Mat',
    pose: 'twist',
    met: 3.8,
    tip: 'Exhale hard at the top of every rep.',
    instructions: ['Knees bent, feet flat', 'Curl the ribs toward the hips', 'Lower one vertebra at a time'],
  },
  {
    id: 'russian-twist',
    name: 'Russian Twists',
    group: 'Core',
    equipment: 'Mat',
    pose: 'twist',
    met: 5,
    tip: 'Rotate through the ribcage, not just the arms.',
    instructions: ['Sit with heels down, torso leaned back', 'Twist to tap beside the hip', 'Keep the chest tall'],
  },
  {
    id: 'leg-raise',
    name: 'Lying Leg Raises',
    group: 'Core',
    equipment: 'Mat',
    pose: 'plank',
    met: 5,
    tip: 'Press the lower back flat into the floor.',
    instructions: ['Legs straight, hands by the hips', 'Raise to 90° under control', 'Lower without touching the floor'],
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climbers',
    group: 'Core',
    equipment: 'None',
    pose: 'climber',
    met: 8,
    tip: 'Hips stay low and level — no bouncing.',
    instructions: ['Start in a high plank', 'Drive one knee toward the chest', 'Alternate fast while breathing rhythmically'],
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Body Hold',
    group: 'Core',
    equipment: 'Mat',
    pose: 'plank',
    met: 4,
    tip: 'Lower back glued to the floor the whole time.',
    instructions: ['Lie on the back, arms overhead', 'Lift shoulders and legs off the floor', 'Hold a shallow banana shape'],
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    group: 'Core',
    equipment: 'Mat',
    pose: 'twist',
    met: 4,
    tip: 'Move the opposite arm and leg slowly, together.',
    instructions: ['Arms up, knees over hips', 'Extend opposite arm and leg', 'Return and switch sides'],
  },
  /* ------------------------------- cardio ------------------------------- */
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    group: 'Full Body',
    equipment: 'None',
    pose: 'jumpjack',
    met: 8,
    tip: 'Land softly through the mid-foot.',
    instructions: ['Feet together, arms by the sides', 'Jump the feet out and arms overhead', 'Return and repeat at pace'],
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    group: 'Full Body',
    equipment: 'None',
    pose: 'run',
    met: 8.5,
    tip: 'Knees to hip height, quick light feet.',
    instructions: ['Run in place with tall posture', 'Drive each knee above the hip', 'Pump the arms in rhythm'],
  },
  {
    id: 'burpee',
    name: 'Burpees',
    group: 'Full Body',
    equipment: 'None',
    pose: 'jump',
    met: 10,
    tip: 'Step back instead of jumping to lower the intensity.',
    instructions: ['Squat, hands to the floor', 'Jump or step back to a plank', 'Push up, jump the feet in, explode up'],
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    group: 'Full Body',
    equipment: 'None',
    pose: 'jumpjack',
    met: 11,
    tip: 'Small hops, wrists do the work.',
    instructions: ['Elbows close to the ribs', 'Turn the rope from the wrists', 'Stay on the balls of the feet'],
  },
  {
    id: 'box-jump',
    name: 'Box Jumps',
    group: 'Legs',
    equipment: 'None',
    pose: 'jump',
    met: 9,
    tip: 'Land soft, step down — protect the Achilles.',
    instructions: ['Load the hips, swing the arms', 'Jump onto the box', 'Stand tall, then step down'],
  },
  {
    id: 'sprint-interval',
    name: 'Sprint Intervals',
    group: 'Legs',
    equipment: 'None',
    pose: 'run',
    met: 12,
    tip: 'Full recovery between reps keeps quality high.',
    instructions: ['Sprint hard for 20–30 seconds', 'Walk or jog to recover', 'Repeat with the same output'],
  },
  {
    id: 'steady-run',
    name: 'Steady State Run',
    group: 'Legs',
    equipment: 'None',
    pose: 'run',
    met: 9.8,
    tip: 'Conversational pace — you should be able to talk.',
    instructions: ['Relaxed shoulders, quick cadence', 'Land under the hips', 'Keep effort at 6–7 out of 10'],
  },
  {
    id: 'incline-walk',
    name: 'Incline Walk',
    group: 'Legs',
    equipment: 'Machine',
    pose: 'run',
    met: 6,
    tip: 'No holding the rails — let the legs carry you.',
    instructions: ['Set the treadmill to 8–12% incline', 'Walk tall without leaning', 'Long, purposeful strides'],
  },
  {
    id: 'rowing-machine',
    name: 'Rowing Machine',
    group: 'Back',
    equipment: 'Machine',
    pose: 'row',
    met: 7,
    tip: 'Legs, then body, then arms — reverse on the way back.',
    instructions: ['Drive with the legs first', 'Swing back, then pull the handle', 'Return arms, body, legs'],
  },
  {
    id: 'stair-climb',
    name: 'Stair Climb',
    group: 'Legs',
    equipment: 'None',
    pose: 'run',
    met: 8.8,
    tip: 'Push through the whole foot, avoid tiptoeing.',
    instructions: ['Climb at a steady pace', 'Keep the torso upright', 'Use the handrail only for balance'],
  },
  /* ------------------------------ full body ------------------------------ */
  {
    id: 'kb-swing',
    name: 'Kettlebell Swings',
    group: 'Full Body',
    equipment: 'Kettlebell',
    pose: 'swing',
    met: 9,
    tip: 'It is a hinge, not a squat. Snap the hips.',
    instructions: ['Hinge and hike the bell back', 'Snap the hips to float the bell', 'Let it swing to chest height'],
  },
  {
    id: 'thruster',
    name: 'Dumbbell Thrusters',
    group: 'Full Body',
    equipment: 'Dumbbells',
    pose: 'press',
    met: 8,
    tip: 'Use the leg drive to launch the press.',
    instructions: ['Front-rack the dumbbells', 'Squat to parallel', 'Stand and press overhead in one flow'],
  },
  {
    id: 'clean-and-press',
    name: 'Clean & Press',
    group: 'Full Body',
    equipment: 'Dumbbells',
    pose: 'press',
    met: 7.5,
    tip: 'Keep the dumbbells close to the body on the clean.',
    instructions: ['Hinge, then pull to the shoulders', 'Stand tall and brace', 'Press overhead, lower with control'],
  },
  {
    id: 'farmer-carry',
    name: 'Farmer Carry',
    group: 'Full Body',
    equipment: 'Dumbbells',
    pose: 'swing',
    met: 6,
    tip: 'Shoulders packed, ribs stacked, walk tall.',
    instructions: ['Hold heavy weights at the sides', 'Walk with short quick steps', 'Do not shrug or lean'],
  },
  {
    id: 'dumbbell-snatch',
    name: 'Dumbbell Snatch',
    group: 'Full Body',
    equipment: 'Dumbbells',
    pose: 'swing',
    met: 8.5,
    tip: 'One fluid motion — the arm is just a hook.',
    instructions: ['Hinge with the bell between the feet', 'Extend the hips explosively', 'Punch overhead to lockout'],
  },
  {
    id: 'renegade-row',
    name: 'Renegade Rows',
    group: 'Back',
    equipment: 'Dumbbells',
    pose: 'row',
    met: 7,
    tip: 'Widen the feet for stability, keep the hips quiet.',
    instructions: ['High plank on dumbbells', 'Row one bell to the hip', 'Alternate without rotating the hips'],
  },
  {
    id: 'bear-crawl',
    name: 'Bear Crawl',
    group: 'Full Body',
    equipment: 'None',
    pose: 'climber',
    met: 7,
    tip: 'Knees hover an inch off the floor.',
    instructions: ['Hands under the shoulders, knees bent', 'Crawl opposite hand and foot', 'Keep the back flat and low'],
  },
  /* ------------------------------- mobility ------------------------------ */
  {
    id: 'cat-cow',
    name: 'Cat Cow',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'stretch',
    met: 2.5,
    tip: 'Move with the breath — inhale to extend, exhale to round.',
    instructions: ['On all fours, neutral spine', 'Arch up on the exhale', 'Drop the belly on the inhale'],
  },
  {
    id: 'downward-dog',
    name: 'Downward Dog',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'stretch',
    met: 3,
    tip: 'Bend the knees to keep the spine long.',
    instructions: ['Hands shoulder-width, hips high', 'Press the floor away', 'Pedal the heels to warm the calves'],
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'lunge',
    met: 2.5,
    tip: 'Tuck the tailbone before you lean forward.',
    instructions: ['Half-kneeling position', 'Squeeze the back glute', 'Shift gently forward and hold'],
  },
  {
    id: 'hamstring-stretch',
    name: 'Hamstring Stretch',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'stretch',
    met: 2.3,
    tip: 'Hinge from the hips, keep the back flat.',
    instructions: ['One leg long, toes up', 'Hinge forward from the hip', 'Hold 30–45 seconds per side'],
  },
  {
    id: 'thread-the-needle',
    name: 'Thread the Needle',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'twist',
    met: 2.8,
    tip: 'Rotate from the upper back, hips stay high.',
    instructions: ['On all fours', 'Slide one arm under the body', 'Rest the shoulder and temple down'],
  },
  {
    id: 'world-greatest-stretch',
    name: "World's Greatest Stretch",
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'lunge',
    met: 3.5,
    tip: 'The best all-in-one warm-up — hold each position 2s.',
    instructions: ['Deep lunge, hands inside the front foot', 'Rotate the same-side arm to the sky', 'Switch sides and repeat'],
  },
  {
    id: 'thoracic-rotation',
    name: 'Thoracic Rotation',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'twist',
    met: 2.8,
    tip: 'Follow the hand with your eyes to get more range.',
    instructions: ['Kneel tall, hand behind the head', 'Rotate the elbow toward the floor', 'Open back up to the ceiling'],
  },
  {
    id: 'ninety-ninety',
    name: '90/90 Hip Switch',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'twist',
    met: 3,
    tip: 'Stay tall — do not roll onto the hip.',
    instructions: ['Both knees at 90°, one forward, one back', 'Rotate side to side', 'Keep the hands behind for support'],
  },
  {
    id: 'childs-pose',
    name: "Child's Pose",
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'stretch',
    met: 2,
    tip: 'Breathe into the lower back for a deeper release.',
    instructions: ['Kneel and sit the hips to the heels', 'Walk the hands forward', 'Rest the forehead down and breathe'],
  },
  {
    id: 'warrior-two',
    name: 'Warrior II',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'stretch',
    met: 3.2,
    tip: 'Front knee over the ankle, arms parallel to the floor.',
    instructions: ['Wide stance, front toes forward', 'Bend the front knee to 90°', 'Gaze over the front fingertips'],
  },
  {
    id: 'tree-pose',
    name: 'Tree Pose',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'stretch',
    met: 2.8,
    tip: 'Fix your eyes on one point to steady the balance.',
    instructions: ['Stand tall, foot on the inner calf or thigh', 'Hands together at the chest', 'Hold and breathe evenly'],
  },
  {
    id: 'triangle-pose',
    name: 'Triangle Pose',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'stretch',
    met: 3,
    tip: 'Lengthen both sides of the waist equally.',
    instructions: ['Wide stance, front foot turned out', 'Reach forward, then hinge down', 'Top arm reaches to the sky'],
  },
  {
    id: 'sun-salutation',
    name: 'Sun Salutation',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'stretch',
    met: 4,
    tip: 'Link every movement to a full breath.',
    instructions: ['Stand, reach overhead and fold', 'Step back, lower and open the chest', 'Flow back to standing'],
  },
  {
    id: 'cobra',
    name: 'Cobra Stretch',
    group: 'Mobility',
    equipment: 'Mat',
    pose: 'stretch',
    met: 2.5,
    tip: 'Push the floor away instead of cranking the neck.',
    instructions: ['Lie face down, hands under the shoulders', 'Press up and open the chest', 'Keep the hips on the floor'],
  },
])

export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(EXERCISES.map((e) => [e.id, e]))

export const getExercise = (id: string): Exercise => EXERCISE_MAP[id] ?? EXERCISES[0]

export const MUSCLE_GROUPS: Exercise['group'][] = ['Chest', 'Back', 'Legs', 'Arms', 'Core', 'Shoulders', 'Glutes', 'Full Body', 'Mobility']

export const EQUIPMENT_LIST: Exercise['equipment'][] = [
  'None',
  'Dumbbells',
  'Barbell',
  'Kettlebell',
  'Resistance Band',
  'Mat',
  'Machine',
  'Pull-up Bar',
]

/** Expand a workout's exercise list into a rest-time map the player uses. */
export const restFor = (plan: WorkoutExercise): number => plan.restSec
